[HACK] pwm-axi-pwmgen: remove pwm_ops that are deprecated
drivers/pwm/pwm-axi-pwmgen.c:124:10: error: ‘const struct pwm_ops’ has no member named ‘disable’
  124 |         .disable = axi_pwmgen_disable,
      |          ^~~~~~~
drivers/pwm/pwm-axi-pwmgen.c:124:20: error: initialization of ‘int (*)(struct pwm_chip *, struct pwm_device *, struct pwm_state *)’ from incompatible pointer type ‘void (*)(struct pwm_chip *, struct pwm_device *)’ [-Werror=incompatible-pointer-types]
  124 |         .disable = axi_pwmgen_disable,
      |                    ^~~~~~~~~~~~~~~~~~
drivers/pwm/pwm-axi-pwmgen.c:124:20: note: (near initialization for ‘axi_pwmgen_pwm_ops.get_state’)
drivers/pwm/pwm-axi-pwmgen.c:125:10: error: ‘const struct pwm_ops’ has no member named ‘enable’
  125 |         .enable = axi_pwmgen_enable,
      |          ^~~~~~